### PR TITLE
bugfix: fix different log colors

### LINKED ISSUE #1584: different log formats
### What happen?

The console prints out different log formats

image

### Relevant log output?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

_No response_

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### What is the Kernel version?

Linux master-172-31-97-104 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by kakaZhou719**
### Describe what this PR does / why we need it

Fix:  different log colors。

### Does this pull request fix one issue?

Fixes #1584

### CODE REVIEW

**Comment by allencloud** [comment]
@kakaZhou719 Could you paste a picture shows what will show now? And it could prove that you made it.

File: pkg/logger/formatter.go [hunk 1]
```diff
@@ -87,10 +87,12 @@ func (f *Formatter) Format(entry *logrus.Entry) ([]byte, error) {
 
 	if !f.DisableColor {
 		levelColor := getColorByLevel(entry.Level)
-		fmt.Fprintf(b, "\x1b[%dm%s\x1b[0m", levelColor, newLog)
+		fmt.Fprintf(b, "\033[%dm%s\033[0m", levelColor, newLog)
```
Comment (allencloud) [inline pkg/logger/formatter.go:90]: Add a comment for this line, otherwise nobody could recognize what this line of code mean. @kakaZhou719

Comment (kakaZhou719) [reply pkg/logger/formatter.go:90]: I didn't modify the log colors, just added the format specification

here is  an color examples:

`var Reset  = "\033[0m"
var Red    = "\033[31m"
var Green  = "\033[32m"
var Yellow = "\033[33m"
var Blue   = "\033[34m"
var Purple = "\033[35m"
var Cyan   = "\033[36m"
var Gray   = "\033[37m"
var White  = "\033[97m"`

**Review by allencloud — APPROVED** [review]
